#pragma once
#include "external_code/glm/glm.hpp"
#include "external_code/glm/gtc/matrix_transform.hpp"
#include <vector>
#include <unordered_map>
#include <sstream>
class GraphicsTurtle
{
private:
	//turtles push/pop matrix operation values
	std::vector<glm::mat4> matrixStack;
	//transforms from origin to current turtle position
	glm::mat4 currentTransformation;
	//storage for distance from origin
	std::vector<float> distanceFromOriginStack;
	//current distance from origin
	float distanceFromOrigin;
	//current branch count
	int branchCount;
	//index of point pushed
	std::vector<unsigned int> indexOfVertexStack;
	//tracks current index we are starting our move operation from
	unsigned int stackIndex;
	//mapped L-system symbols to turtle instructions and magnitudes
	std::unordered_map<char, std::pair<char, float>> LSystemToTurtleMappings;

	//flag for whether we popped last instruction
	bool poppedLastInstruction;

public:
	GraphicsTurtle();
	
	//vertex data
	struct vertex {
		float position[3];
		float colour[4];
		float distanceFromOrigin;
		float circleNormal[3];
		int branchCount;
		bool isLeaf;
	};

	//graphics information
	struct renderData {
		std::vector<vertex> vertexes;
		std::vector<unsigned> indexes;
		float maximumDistanceFromOrigin;
	};

	//Turtle drawing functions
	void MoveForward(float amount, bool penDown);
	void RotateYaw(float rotation);
	void RotatePitch(float rotation);
	void RotateRoll(float rotation);
	void PushMatrix();
	void PopMatrix();
	
	/*function BuildLSystemToTurtleMappings(std::string turtleRules)
	* parameters:
	*	turtleRules: string containing the conversion information between L-System symbols
	*		and turtle symbols.
	*		format = "A-F X,B-f Z,..."
	*		A and B = L-system symbols
	*		F and f = turtle instruction
	*		X and Z = turtle instruction magnitude, leave empty if pop/push
	* purpose: To initialize a turtles instruction set to be able to understand instructions from a specific L-System string
	* returns: N/A
	*/
	void BuildLSystemToTurtleMappings(std::string turtleRules);
	
	/*function GenerateGeometryOfLSystemRuleString(std::string rules)
	* parameters:
	*	rules: string containing the output of an L-system at a generation
	*		format = "ABCDE[]DD0123OF..."
	*		just make sure every symbol present in the string has an entry in the turtles mappings
	* purpose: To generate geometry using an L-system given a ruleset already loaded into the turtle
	*	From calling BuildLSystemToTurtleMappings(std::string turtleRules) with the L-system rule mappings
	* returns: renderData struct of the geometry generated by the turtle following the instructions
	*/
	renderData GenerateGeometryOfLSystemRuleString(std::string rules);
	
	
	void Reset();
};